spring:
  application:
    name: librarycore
  datasource:
    url: jdbc:postgresql://localhost:5434/library
    username: postgres
    password: root
  liquibase:
      change-log: classpath:db/changelog-master.yaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

