server:
  port: 8082
spring:
  application:
    name: librarycore
  datasource:
    url: jdbc:postgresql://localhost:5434/library
    username: postgres
    password: root
  liquibase:
      change-log: classpath:db/changelog-master.yaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  kafka:
    consumer:
      enable-auto-commit: false
      bootstrap-servers: localhost:9092
      group-id: core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    listener:
      ack-mode: MANUAL
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
jwt:
  secret: 'secreteeffffffffffffffffffffffffffffffffffffffffffaf'
apiKeys:
  authServiceApiKey: testApi
  asd: das
kafka:
  registrationEventsListenerEnabled: true

