server:
  port: 8081
spring:
  application:
    name: libraryAuth
  datasource:
    url: jdbc:postgresql://localhost:5434/library_auth
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
jwt:
  ttlMinutes: 5
  secret: 'secreteeffffffffffffffffffffffffffffffffffffffffffaf'

