server:
  port: 8081
spring:
  application:
    name: libraryAuth
  datasource:
    url: jdbc:postgresql://localhost:5434/library_auth
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
jwt:
  ttlMinutes: 5
  secret: 'secreteeffffffffffffffffffffffffffffffffffffffffffaf'
apiKeys:
  customApiKey: testApi
core:
  exchangeMode: async
  url:
    userController: 'http://localhost:8082/api/v1/inner/user'
